### ISSUE TITLE
Error interno

### ISSUE THREAD

**Issue by avdata99** [avdata99/ckan-env#49]
Error en página /api/1/util/snippet/api_info.html

<pre>
Traceback (most recent call last):
  File "/app/unckan/venv/lib/python3.11/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/ckan/config/middleware/../../views/api.py", line 496, in snippet
    return render(snippet_path, extra_vars=extra_vars)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/ckan/lib/base.py", line 107, in render
    return flask_render_template(template_name, **extra_vars)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
    return _render(
           ^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/app/unckan/venv/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/unckan/venv/lib/python3.11/site-packages/ckanext/datastore/templates/ajax_snippets/api_info.html", line 13, in top-level template code
    {% set resource_id = h.sanitize_id(resource_id) %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/unckan/venv/lib/python3.11/site-packages/ckan/lib/helpers.py", line 2679, in sanitize_id
    return str(uuid.UUID(id_))
               ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/uuid.py", line 178, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
<b>ValueError: badly formed hexadecimal UUID string</b>
</pre>

**Comment by avdata99** [comment]
Posiblemente hay algun recurso con alguna falla o un ID mal definido
